# Generated by Django 5.2.16 on 2026-07-24 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('verified_citizen', 'Verified citizen'), ('official', 'Official'), ('moderator', 'Moderator'), ('system_admin', 'System administrator')], default='citizen', max_length=24)),
                ('citizen_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('verified_municipality_code', models.CharField(blank=True, max_length=20)),
                ('verified_ward_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=160)),
                ('subject_key', models.CharField(max_length=64)),
                ('token_identifier_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected')], max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='accounts.citizenprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
