# Generated by Django 5.2.16 on 2026-07-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable API code, e.g. 2081-82', max_length=12, unique=True)),
                ('year_bs', models.CharField(help_text='Bikram Sambat, e.g. 2081/82', max_length=12, unique=True)),
                ('year_ad', models.CharField(help_text='Gregorian, e.g. 2024/25', max_length=12, unique=True)),
                ('label_np', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_np', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='SubSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_np', models.CharField(max_length=150)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsectors', to='budgets.sector')),
            ],
            options={
                'ordering': ['sector__name_en', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_type', models.CharField(choices=[('recurrent', 'Recurrent'), ('capital', 'Capital'), ('financing', 'Financing')], max_length=12)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('spent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('data_classification', models.CharField(choices=[('official', 'Official'), ('reconstructed_from_official_sources', 'Reconstructed from official sources'), ('curated_demo', 'Curated demo'), ('synthetic_demo', 'Synthetic demo')], default='synthetic_demo', max_length=40)),
                ('source_url', models.URLField(blank=True)),
                ('local_government', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_allocations', to='geography.localgovernment')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_allocations', to='budgets.fiscalyear')),
                ('subsector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_allocations', to='budgets.subsector')),
            ],
            options={
                'ordering': ['local_government__name_en', '-fiscal_year__code', 'subsector__name_en'],
                'indexes': [models.Index(fields=['local_government', 'fiscal_year', 'budget_type'], name='budgets_bud_local_g_1d71f6_idx')],
                'constraints': [models.UniqueConstraint(fields=('local_government', 'fiscal_year', 'subsector', 'budget_type'), name='unique_local_fy_subsector_budget_type'), models.CheckConstraint(condition=models.Q(('allocated_amount__gte', 0)), name='allocation_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('spent_amount__isnull', True), ('spent_amount__gte', 0), _connector='OR'), name='allocation_spent_nonnegative_or_unknown')],
            },
        ),
    ]
