# Generated by Django 5.2.16 on 2026-07-23 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title_en', models.CharField(max_length=240)),
                ('title_np', models.CharField(max_length=240)),
                ('description_en', models.TextField(blank=True)),
                ('description_np', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('procurement', 'Procurement'), ('implementation', 'Implementation'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('on_hold', 'On hold')], max_length=20)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('official_progress_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('data_classification', models.CharField(choices=[('official', 'Official'), ('reconstructed_from_official_sources', 'Reconstructed from official sources'), ('curated_demo', 'Curated demo'), ('synthetic_demo', 'Synthetic demo')], default='synthetic_demo', max_length=40)),
                ('data_note_en', models.CharField(blank=True, max_length=300)),
                ('data_note_np', models.CharField(blank=True, max_length=300)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='budgets.budgetallocation')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='budgets.fiscalyear')),
                ('local_government', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='geography.localgovernment')),
                ('subsector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='budgets.subsector')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='geography.ward')),
            ],
            options={
                'ordering': ['-fiscal_year__code', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('label_en', models.CharField(blank=True, max_length=200)),
                ('label_np', models.CharField(blank=True, max_length=200)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('title_en', models.CharField(max_length=200)),
                ('title_np', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('delayed', 'Delayed')], max_length=20)),
                ('progress_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['local_government', 'fiscal_year', 'status'], name='projects_pr_local_g_62b2fb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['subsector', 'status'], name='projects_pr_subsect_b0da2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gte', 0)), name='project_allocated_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('official_progress_percent__isnull', True), models.Q(('official_progress_percent__gte', 0), ('official_progress_percent__lte', 100)), _connector='OR'), name='project_progress_between_0_and_100_or_unknown'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('planned_start_date__isnull', True), ('planned_end_date__isnull', True), ('planned_end_date__gte', models.F('planned_start_date')), _connector='OR'), name='project_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='projectlocation',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='project_latitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectlocation',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='project_longitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectmilestone',
            constraint=models.UniqueConstraint(fields=('project', 'sequence'), name='unique_project_milestone_sequence'),
        ),
        migrations.AddConstraint(
            model_name='projectmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='milestone_progress_between_0_and_100'),
        ),
    ]
