# Generated by Django 5.2.16 on 2026-07-24 06:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_allocation_unknown"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectEvidenceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("agreement_recorded", "Agreement recorded"),
                            ("monitoring_recorded", "Monitoring recorded"),
                            ("payment_date_recorded", "Payment date recorded"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "date_bs",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="BS date must use YYYY/MM/DD format.",
                                regex="^\\d{4}/\\d{2}/\\d{2}$",
                            )
                        ],
                    ),
                ),
                ("date_ad", models.DateField(blank=True, null=True)),
                ("source_page", models.PositiveIntegerField()),
                ("source_url", models.URLField(blank=True)),
                ("note_en", models.CharField(blank=True, max_length=240)),
                ("note_np", models.CharField(blank=True, max_length=240)),
                (
                    "data_classification",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            (
                                "reconstructed_from_official_sources",
                                "Reconstructed from official sources",
                            ),
                            ("curated_demo", "Curated demo"),
                            ("synthetic_demo", "Synthetic demo"),
                        ],
                        default="official",
                        max_length=40,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_events",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["source_page", "event_type", "date_bs"],
                "indexes": [
                    models.Index(
                        fields=["project", "event_type"], name="projects_pr_project_ce7484_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "event_type", "date_bs"),
                        name="unique_project_evidence_event_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_page__gte", 1)),
                        name="project_evidence_event_source_page_positive",
                    ),
                ],
            },
        ),
    ]
