# Generated by Django 5.2.16 on 2026-07-24 02:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_project_allocation_unknown'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_id', models.CharField(max_length=80)),
                ('rule_version', models.PositiveSmallIntegerField(default=1)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=12)),
                ('reliability', models.CharField(choices=[('limited', 'Limited evidence'), ('moderate', 'Moderate'), ('strong', 'Strong'), ('official_reference', 'Official reference')], max_length=24)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=12)),
                ('title_en', models.CharField(max_length=240)),
                ('title_np', models.CharField(max_length=240)),
                ('reason_en', models.TextField()),
                ('reason_np', models.TextField()),
                ('data_used', models.JSONField(default=dict)),
                ('threshold', models.JSONField(default=dict)),
                ('calculated_values', models.JSONField(default=dict)),
                ('possible_explanations', models.JSONField(default=list)),
                ('recommendation_en', models.TextField()),
                ('recommendation_np', models.TextField()),
                ('source_references', models.JSONField(default=list)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_evaluated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_flags', to='projects.project')),
            ],
            options={
                'ordering': ['-severity', 'rule_id'],
                'indexes': [models.Index(fields=['project', 'status', 'severity'], name='anomalies_a_project_68df67_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'rule_id'), name='unique_anomaly_rule_per_project')],
            },
        ),
    ]
