# Generated by Django 5.2.16 on 2026-07-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('paid_on', models.DateField()),
                ('description_en', models.CharField(blank=True, max_length=240)),
                ('description_np', models.CharField(blank=True, max_length=240)),
                ('source_url', models.URLField(blank=True)),
                ('data_classification', models.CharField(choices=[('official', 'Official'), ('reconstructed_from_official_sources', 'Reconstructed from official sources'), ('curated_demo', 'Curated demo'), ('synthetic_demo', 'Synthetic demo')], default='synthetic_demo', max_length=40)),
                ('contract_award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='procurement.contractaward')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='projects.projectmilestone')),
            ],
            options={
                'ordering': ['paid_on', 'reference'],
                'indexes': [models.Index(fields=['contract_award', 'paid_on'], name='payments_pa_contrac_1274a5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_nonnegative')],
            },
        ),
    ]
