# Generated by Django 5.2.16 on 2026-07-23 12:15

import django.core.validators
import django.db.models.deletion
import documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('geography', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=300)),
                ('title_np', models.CharField(blank=True, max_length=300)),
                ('document_type', models.CharField(choices=[('budget_book', 'Budget book / red book'), ('budget_speech', 'Budget speech'), ('annual_program', 'Annual policy or program'), ('economic_act', 'Economic act or bill'), ('progress_report', 'Progress report'), ('procurement_notice', 'Procurement notice'), ('contract_award', 'Contract award'), ('payment_record', 'Payment record'), ('audit_report', 'Audit report'), ('other', 'Other')], max_length=30)),
                ('language', models.CharField(choices=[('nep', 'Nepali'), ('eng', 'English'), ('nep+eng', 'Nepali and English')], max_length=10)),
                ('original_file', models.FileField(blank=True, upload_to=documents.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=260)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_url', models.URLField(max_length=1000)),
                ('source_url_kind', models.CharField(choices=[('direct_pdf', 'Direct PDF'), ('landing_page', 'Official landing page')], default='direct_pdf', max_length=20)),
                ('source_note', models.CharField(blank=True, max_length=500)),
                ('data_classification', models.CharField(choices=[('official', 'Official'), ('reconstructed_from_official_sources', 'Reconstructed from official sources'), ('curated_demo', 'Curated demo'), ('synthetic_demo', 'Synthetic demo')], default='official', max_length=40)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('extraction_error', models.CharField(blank=True, max_length=500)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_documents', to='budgets.fiscalyear')),
                ('local_government', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_documents', to='geography.localgovernment')),
            ],
            options={
                'ordering': ['-fiscal_year__code', 'local_government__name_en', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('context', 'Municipal context'), ('allocation', 'Budget allocation'), ('procurement', 'Procurement'), ('payment', 'Payment'), ('progress', 'Progress'), ('completion', 'Completion')], max_length=20)),
                ('page_from', models.PositiveIntegerField(blank=True, null=True)),
                ('page_to', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=240)),
                ('evidence_note_en', models.CharField(max_length=500)),
                ('evidence_note_np', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='projects.project')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ['relationship', 'document__title_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('section', models.CharField(blank=True, max_length=240)),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_method', models.CharField(choices=[('embedded_text', 'Embedded text'), ('ocr', 'Optical character recognition'), ('none', 'No usable text')], default='none', max_length=20)),
                ('text_quality_score', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('auto_accepted', 'Auto-accepted'), ('review_required', 'Review required'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('extraction_warnings', models.JSONField(blank=True, default=list)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='DataExtractionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('needs_review', 'Needs review'), ('failed', 'Failed')], max_length=20)),
                ('extractor_version', models.CharField(max_length=100)),
                ('ocr_languages', models.CharField(blank=True, max_length=40)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('embedded_text_pages', models.PositiveIntegerField(default=0)),
                ('ocr_pages', models.PositiveIntegerField(default=0)),
                ('failed_pages', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_records', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('section', models.CharField(blank=True, max_length=240)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('vector_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.documentpage')),
            ],
            options={
                'ordering': ['page__page_number', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('page', 'chunk_index'), name='unique_chunk_index_per_page')],
            },
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['local_government', 'fiscal_year', 'document_type'], name='documents_s_local_g_e9266d_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['processing_status', 'document_type'], name='documents_s_process_cf1d76_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('sha256', ''), _negated=True), fields=('sha256',), name='unique_nonempty_document_sha256'),
        ),
        migrations.AddConstraint(
            model_name='projectdocumentlink',
            constraint=models.UniqueConstraint(fields=('project', 'document', 'relationship'), name='unique_project_document_relationship'),
        ),
        migrations.AddConstraint(
            model_name='projectdocumentlink',
            constraint=models.CheckConstraint(condition=models.Q(('page_from__isnull', True), ('page_from__gte', 1), _connector='OR'), name='project_document_page_from_positive'),
        ),
        migrations.AddConstraint(
            model_name='projectdocumentlink',
            constraint=models.CheckConstraint(condition=models.Q(('page_to__isnull', True), ('page_to__gte', 1), _connector='OR'), name='project_document_page_to_positive'),
        ),
        migrations.AddConstraint(
            model_name='projectdocumentlink',
            constraint=models.CheckConstraint(condition=models.Q(('page_from__isnull', True), ('page_to__isnull', True), ('page_to__gte', models.F('page_from')), _connector='OR'), name='project_document_page_range_valid'),
        ),
        migrations.AddIndex(
            model_name='documentpage',
            index=models.Index(fields=['document', 'review_status'], name='documents_d_documen_cbba29_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpage',
            index=models.Index(fields=['extraction_method', 'review_status'], name='documents_d_extract_d6000f_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentpage',
            constraint=models.UniqueConstraint(fields=('document', 'page_number'), name='unique_page_number_per_document'),
        ),
        migrations.AddConstraint(
            model_name='documentpage',
            constraint=models.CheckConstraint(condition=models.Q(('page_number__gte', 1)), name='document_page_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='documentpage',
            constraint=models.CheckConstraint(condition=models.Q(('text_quality_score__gte', 0), ('text_quality_score__lte', 1)), name='document_page_quality_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='documentpage',
            constraint=models.CheckConstraint(condition=models.Q(('ocr_confidence__isnull', True), models.Q(('ocr_confidence__gte', 0), ('ocr_confidence__lte', 100)), _connector='OR'), name='document_page_ocr_confidence_valid'),
        ),
    ]
