# Generated by Django 5.2.16 on 2026-07-23 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_np', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_np', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='LocalGovernment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_np', models.CharField(max_length=150)),
                ('government_type', models.CharField(choices=[('metropolitan', 'Metropolitan city'), ('sub_metropolitan', 'Sub-metropolitan city'), ('municipality', 'Municipality'), ('rural_municipality', 'Rural municipality')], max_length=24)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_governments', to='geography.district')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='geography.province'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('name_np', models.CharField(blank=True, max_length=100)),
                ('local_government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='geography.localgovernment')),
            ],
            options={
                'ordering': ['local_government__name_en', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='localgovernment',
            index=models.Index(fields=['government_type', 'name_en'], name='geography_l_governm_aba610_idx'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('local_government', 'number'), name='unique_ward_per_local_government'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 99)), name='ward_number_between_1_and_99'),
        ),
    ]
