# Generated by Django 5.2.16 on 2026-07-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('municipality_name', models.CharField(blank=True, max_length=150)),
                ('data_classification', models.CharField(choices=[('official', 'Official'), ('reconstructed_from_official_sources', 'Reconstructed from official sources'), ('curated_demo', 'Curated demo'), ('synthetic_demo', 'Synthetic demo')], default='synthetic_demo', max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('title_en', models.CharField(max_length=240)),
                ('title_np', models.CharField(max_length=240)),
                ('procurement_method', models.CharField(choices=[('open_competitive', 'Open competitive bidding'), ('sealed_quotation', 'Sealed quotation'), ('direct', 'Direct procurement'), ('other', 'Other')], max_length=30)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('data_classification', models.CharField(choices=[('official', 'Official'), ('reconstructed_from_official_sources', 'Reconstructed from official sources'), ('curated_demo', 'Curated demo'), ('synthetic_demo', 'Synthetic demo')], default='synthetic_demo', max_length=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='projects.project')),
            ],
            options={
                'ordering': ['published_date', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='ContractAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_reference', models.CharField(max_length=80, unique=True)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('awarded_date', models.DateField(blank=True, null=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('data_classification', models.CharField(choices=[('official', 'Official'), ('reconstructed_from_official_sources', 'Reconstructed from official sources'), ('curated_demo', 'Curated demo'), ('synthetic_demo', 'Synthetic demo')], default='synthetic_demo', max_length=40)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_awards', to='procurement.contractor')),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='procurement.tender')),
            ],
            options={
                'ordering': ['-awarded_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='tender',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_amount__isnull', True), ('estimated_amount__gte', 0), _connector='OR'), name='tender_estimated_amount_nonnegative_or_unknown'),
        ),
        migrations.AddConstraint(
            model_name='contractaward',
            constraint=models.CheckConstraint(condition=models.Q(('contract_amount__gte', 0)), name='contract_award_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='contractaward',
            constraint=models.CheckConstraint(condition=models.Q(('contract_start_date__isnull', True), ('contract_end_date__isnull', True), ('contract_end_date__gte', models.F('contract_start_date')), _connector='OR'), name='contract_end_not_before_start'),
        ),
    ]
