# Generated by Django 5.2.16 on 2026-07-24 02:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0003_project_allocation_unknown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completion_rating', models.PositiveSmallIntegerField()),
                ('quality_rating', models.PositiveSmallIntegerField()),
                ('usefulness_rating', models.PositiveSmallIntegerField()),
                ('allocation_fairness_rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('directly_observed', models.BooleanField(default=False)),
                ('is_local_resident', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified citizen'), ('verified', 'Verified citizen'), ('verified_local', 'Verified local resident')], default='unverified', max_length=20)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='accounts.citizenprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_summary', models.JSONField(default=dict)),
                ('after_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='feedback.citizenfeedback')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_records', to='feedback.citizenfeedback')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='citizenfeedback',
            index=models.Index(fields=['project', 'verification_status'], name='feedback_ci_project_4516e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='citizenfeedback',
            constraint=models.UniqueConstraint(fields=('citizen_profile', 'project'), name='one_feedback_per_citizen_project', violation_error_code='duplicate_feedback'),
        ),
        migrations.AddConstraint(
            model_name='citizenfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('completion_rating__gte', 1), ('completion_rating__lte', 5)), name='feedback_completion_rating_between_1_and_5'),
        ),
        migrations.AddConstraint(
            model_name='citizenfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('quality_rating__gte', 1), ('quality_rating__lte', 5)), name='feedback_quality_rating_between_1_and_5'),
        ),
        migrations.AddConstraint(
            model_name='citizenfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('usefulness_rating__gte', 1), ('usefulness_rating__lte', 5)), name='feedback_usefulness_rating_between_1_and_5'),
        ),
        migrations.AddConstraint(
            model_name='citizenfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('allocation_fairness_rating__gte', 1), ('allocation_fairness_rating__lte', 5)), name='feedback_allocation_fairness_rating_between_1_and_5'),
        ),
    ]
